name: Run Flask Application

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Flask app
        env:
          FLASK_APP: app.py
        run: |
          nohup python app.py &
          sleep 10
          curl http://localhost:5000/
          curl http://localhost:5000/api/students
