name: PR from Issue Command

on:
  issue_comment:
    types: [created]

jobs:
  create-pr:
    if: github.event.comment.body == '/create-pr add-flask-workflow master'
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          branch: add-flask-workflow
          title: "Automated PR: add-flask-workflow to master"
          body: "This PR was triggered by an issue comment."
